apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "n8n.fullname" . }}-config
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.n8n.config }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}