{{- if .Values.n8n.workers.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "n8n.fullname" . }}-worker
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.n8n.workers.replicaCount }}
  selector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "n8n.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      containers:
      - name: n8n-worker
        image: "{{ .Values.n8n.image.registry }}/{{ .Values.n8n.image.repository }}:{{ .Values.n8n.image.tag }}"
        imagePullPolicy: {{ .Values.n8n.image.pullPolicy }}
        command: ["n8n", "worker"]
        env:
        {{- range $key, $value := .Values.n8n.config }}
        - name: {{ $key }}
          value: {{ tpl $value $ | quote }}
        {{- end }}
        # Database Password
        - name: DB_POSTGRESDB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.n8n.secrets.database.passwordSecretName | default (printf "%s-secret" (include "n8n.fullname" .)) }}
              key: {{ .Values.n8n.secrets.database.passwordSecretKey }}
        # Redis Password (if enabled)
        {{- if and .Values.redis.enabled (hasKey .Values.redis "security") .Values.redis.security.authEnabled }}
        - name: QUEUE_BULL_REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.n8n.secrets.redis.passwordSecretName | default (printf "%s-secret" (include "n8n.fullname" .)) }}
              key: {{ .Values.n8n.secrets.redis.passwordSecretKey }}
        {{- end }}
        # Encryption Key
        - name: N8N_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.n8n.secrets.encryption.keySecretName | default (printf "%s-secret" (include "n8n.fullname" .)) }}
              key: {{ .Values.n8n.secrets.encryption.keySecretKey }}
        resources:
          {{- toYaml .Values.n8n.workers.resources | nindent 10 }}
        volumeMounts:
        - name: n8n-data
          mountPath: /home/node/.n8n
      volumes:
      - name: n8n-data
        persistentVolumeClaim:
          claimName: {{ include "n8n.fullname" . }}-pvc
{{- end }}