{{- if .Values.n8n.secrets.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "n8n.fullname" . }}-external-secret
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.n8n.secrets.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.n8n.secrets.externalSecrets.secretStore.name }}
    kind: {{ .Values.n8n.secrets.externalSecrets.secretStore.kind }}
  target:
    name: {{ .Values.n8n.secrets.externalSecrets.targetName }}
    creationPolicy: {{ .Values.n8n.secrets.externalSecrets.creationPolicy }}
  data:
    {{- range .Values.n8n.secrets.externalSecrets.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        property: {{ .remoteRef.property }}
    {{- end }}
{{- end }}
