{{- if and .Values.n8n.workers.enabled .Values.n8n.workers.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "n8n.fullname" . }}-worker-hpa
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "n8n.fullname" . }}-worker
  minReplicas: {{ .Values.n8n.workers.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.n8n.workers.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.n8n.workers.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.n8n.workers.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}