{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "n8n.fullname" . }}-ingress
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    {{- end }}
    nginx.ingress.kubernetes.io/proxy-body-size: {{ .Values.ingress.nginx.proxyBodySize | default "32m" | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.nginx.proxyReadTimeout | default "300" | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ .Values.ingress.nginx.proxySendTimeout | default "300" | quote }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ .Values.ingress.nginx.sslRedirect | default "false" | quote }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: {{ .Values.ingress.nginx.forceSslRedirect | default "false" | quote }}
    nginx.ingress.kubernetes.io/rate-limit: {{ .Values.ingress.rateLimit.requests | default "200" | quote }}
    nginx.ingress.kubernetes.io/rate-limit-window: {{ .Values.ingress.rateLimit.window | default "1m" | quote }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  - host: {{ .Values.ingress.main.subdomain }}.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "n8n.fullname" . }}-main
            port:
              number: 5678
  {{- if .Values.n8n.webhooks.enabled }}
  - host: {{ .Values.ingress.webhooks.subdomain }}.{{ .Values.global.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "n8n.fullname" . }}-webhook
            port:
              number: 5678
      # MCP Support - rota para webhook service
      {{- if .Values.ingress.mcp.enabled }}
      - path: /mcp/
        pathType: Prefix
        backend:
          service:
            name: {{ include "n8n.fullname" . }}-webhook
            port:
              number: 5678
      {{- end }}
  {{- end }}
{{- end }}