{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "n8n.fullname" . }}-netpol
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "n8n.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- with .Values.networkPolicy.policyTypes }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 5678
  - from:
    - podSelector:
        matchLabels:
          {{- include "n8n.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 5678
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: postgresql
    ports:
    - protocol: TCP
      port: 5432
  - to:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: redis
    ports:
    - protocol: TCP
      port: 6379
  - to: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
{{- end }}