apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-main
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: main
spec:
  type: {{ .Values.service.main.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.main.port | default 5678 }}
    targetPort: {{ .Values.service.main.targetPort | default 5678 }}
    protocol: TCP
    name: http
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: main
---
{{- if .Values.n8n.webhooks.enabled | default true }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n.fullname" . }}-webhook
  labels:
    {{- include "n8n.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: {{ .Values.service.webhooks.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.service.webhooks.port | default 5678 }}
    targetPort: {{ .Values.service.webhooks.targetPort | default 5678 }}
    protocol: TCP
    name: http
  selector:
    {{- include "n8n.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
{{- end }}
